import Navbar from "./components/Navbar";
import UseContext from "./context/UseContext";

import "./globals.css";
import Socketio from "./socketContext/socketContext.jsx";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UseContext>
          <Socketio>
            <Navbar />
            {children}
          </Socketio>
        </UseContext>
      </body>
    </html>
  );
}
